apiVersion: v1
kind: Template
metadata:
  name: wfswarm-rest-http-crud
parameters:
- name: SOURCE_REPOSITORY_URL
  description: The source URL for the application
  displayName: Source URL
  value: https://github.com/wildfly-swarm-openshiftio-boosters/wfswarm-rest-http-crud.git
  required: true
- name: SOURCE_REPOSITORY_REF
  description: The branch name for the application
  displayName: Source Branch
  value: master
  required: true
- name: SOURCE_REPOSITORY_DIR
  description: The location within the source repo of the application
  displayName: Source Directory
  value: .
  required: true
- name: GITHUB_WEBHOOK_SECRET
  description: A secret string used to configure the GitHub webhook.
  displayName: GitHub Webhook Secret
  required: true
  from: '[a-zA-Z0-9]{40}'
  generate: expression
objects:
- apiVersion: v1
  kind: ImageStream
  metadata:
    name: wfswarm-rest-http-crud
  spec: {}
- apiVersion: v1
  kind: ImageStream
  metadata:
    name: runtime
  spec:
    tags:
    - name: latest
      from:
        kind: DockerImage
        name: registry.access.redhat.com/redhat-openjdk-18/openjdk18-openshift
- apiVersion: v1
  kind: BuildConfig
  metadata:
    name: wfswarm-rest-http-crud
  spec:
    output:
      to:
        kind: ImageStreamTag
        name: wfswarm-rest-http-crud:latest
    postCommit: {}
    resources: {}
    source:
      git:
        uri: ${SOURCE_REPOSITORY_URL}
        ref: ${SOURCE_REPOSITORY_REF}
      #contextDir: ${SOURCE_REPOSITORY_DIR}
      type: Git
    strategy:
      sourceStrategy:
        from:
          kind: ImageStreamTag
          name: runtime:latest
        incremental: true
        env:
        - name: MAVEN_ARGS_APPEND
          value: "-pl ${SOURCE_REPOSITORY_DIR}"
        - name: ARTIFACT_DIR
          value: "${SOURCE_REPOSITORY_DIR}/target"
      type: Source
    triggers:
    - github:
        secret: ${GITHUB_WEBHOOK_SECRET}
      type: GitHub
    - type: ConfigChange
    - imageChange: {}
      type: ImageChange
  status:
    lastVersion: 0
- apiVersion: v1
  kind: Secret
  metadata:
    labels:
      app: wfswarm-rest-http-crud
      group: io.openshift.boosters
    name: my-database-secret
  stringData:
    user: luke
    password: secret
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      expose: "true"
      app: wfswarm-rest-http-crud
      group: io.openshift.boosters
    name: wfswarm-rest-http-crud
  spec:
    ports:
    - name: http
      port: 8080
      protocol: TCP
      targetPort: 8080
    selector:
      app: wfswarm-rest-http-crud
      group: io.openshift.boosters
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    labels:
      app: wfswarm-rest-http-crud
      group: io.openshift.boosters
    name: wfswarm-rest-http-crud
  spec:
    replicas: 1
    revisionHistoryLimit: 2
    selector:
      app: wfswarm-rest-http-crud
      group: io.openshift.boosters
    strategy:
      rollingParams:
        timeoutSeconds: 3600
      type: Rolling
    template:
      metadata:
        labels:
          app: wfswarm-rest-http-crud
          group: io.openshift.boosters
      spec:
        containers:
        - env:
          - name: DB_USERNAME
            valueFrom:
              secretKeyRef:
                key: user
                name: my-database-secret
          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                key: password
                name: my-database-secret
          - name: GC_MAX_METASPACE_SIZE
            value: "150"
          - name: JAVA_OPTIONS
            value: -Dswarm.datasources.data-sources.MyDS.connection-url=jdbc:postgresql://$(MY_DATABASE_SERVICE_HOST):$(MY_DATABASE_SERVICE_PORT)/my_data
              -Dswarm.datasources.data-sources.MyDS.user-name=$(DB_USERNAME) -Dswarm.datasources.data-sources.MyDS.password=$(DB_PASSWORD)
              -Dswarm.datasources.data-sources.MyDS.driver-name=postgresql
          - name: KUBERNETES_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          image: wfswarm-rest-http-crud:latest
          imagePullPolicy: IfNotPresent
          livenessProbe:
            httpGet:
              path: /
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 180
          name: wildfly-swarm
          ports:
          - containerPort: 8080
            name: http
            protocol: TCP
          - containerPort: 9779
            name: prometheus
            protocol: TCP
          - containerPort: 8778
            name: jolokia
            protocol: TCP
          readinessProbe:
            httpGet:
              path: /
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 10
          securityContext:
            privileged: false
    triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
        - wildfly-swarm
        from:
          kind: ImageStreamTag
          name: wfswarm-rest-http-crud:latest
      type: ImageChange
- apiVersion: v1
  kind: Route
  metadata:
    labels:
      app: wfswarm-rest-http-crud
      group: io.openshift.boosters
    name: wfswarm-rest-http-crud
  spec:
    port:
      targetPort: 8080
    to:
      kind: Service
      name: wfswarm-rest-http-crud
