apiVersion: v1
kind: List
items:
- apiVersion: image.openshift.io/v1
  kind: ImageStream
  metadata:
    labels:
      app: my-database
    name: my-database
  spec:
    lookupPolicy:
      local: false
    tags:
    - name: latest
      from:
        kind: DockerImage
        name: registry.access.redhat.com/rhscl/postgresql-10-rhel7
- apiVersion: apps.openshift.io/v1
  kind: DeploymentConfig
  metadata:
    name: my-database
    labels:
      app: my-database
  spec:
    replicas: 1
    selector:
      app: my-database
      deploymentconfig: my-database
    template:
      metadata:
        labels:
          app: my-database
          deploymentconfig: my-database
      spec:
        containers:
        - name: my-database
          image: ''
          env:
          - name: POSTGRESQL_DATABASE
            value: my_data
          - name: POSTGRESQL_PASSWORD
            value: secret
          - name: POSTGRESQL_USER
            value: luke
          ports:
          - containerPort: 5432
            protocol: TCP
          volumeMounts:
          - name: my-database-volume
            mountPath: /var/lib/pgsql/data
        volumes:
        - name: my-database-volume
          emptyDir: {}
    triggers:
    - type: ConfigChange
    - type: ImageChange
      imageChangeParams:
        automatic: true
        containerNames:
        - my-database
        from:
          kind: ImageStreamTag
          name: my-database:latest
- apiVersion: v1
  kind: Service
  metadata:
    name: my-database
    labels:
      app: my-database
  spec:
    ports:
    - name: 5432-tcp
      port: 5432
      protocol: TCP
      targetPort: 5432
    selector:
      app: my-database
      deploymentconfig: my-database
